/**
 * تمام متن‌های قابل نمایش در یک فایل متمرکز شده‌اند. برای افزودن زبان دیگر
 * کافی است فایل مشابهی با همان ساختار ساخته و در src/constants/strings.ts
 * جایگزین شود.
 */
export const faStrings = {
  app: {
    name: 'کلمه‌ساز',
    tagline: 'با حروف، کلمه بساز',
  },

  common: {
    continue: 'ادامه',
    next: 'مرحله بعد',
    retry: 'تکرار مرحله',
    home: 'خانه',
    back: 'بازگشت',
    close: 'بستن',
    cancel: 'انصراف',
    confirm: 'تأیید',
    save: 'ذخیره',
    later: 'بعداً',
    start: 'شروع',
    claim: 'دریافت جایزه',
    gotIt: 'متوجه شدم',
    loading: 'در حال آماده‌سازی…',
    level: 'مرحله',
    levelNumber: 'مرحله {number}',
    words: 'کلمه',
    of: 'از',
    new: 'جدید',
    locked: 'قفل',
  },

  onboarding: {
    slide1Title: 'حروف را انتخاب کن',
    slide1Body: 'انگشتت را روی حروف بکش (یا یکی‌یکی بزن) و کلمه را بساز.',
    slide2Title: 'کلمه بساز',
    slide2Body: 'با دکمه «بررسی» کلمه‌ات را ثبت کن؛ هر کلمه درست امتیاز و سکه می‌دهد.',
    slide3Title: 'جایزه بگیر',
    slide3Body: 'با سکه‌ها راهنما بخر، مرحله‌های تازه باز کن و چالش روزانه را از دست نده.',
    skip: 'رد کردن',
    startGame: 'شروع بازی',
    pageIndicator: 'صفحه {current} از {total}',
  },

  home: {
    greeting: 'سلام!',
    playButton: 'ادامه بازی',
    playNewButton: 'شروع بازی',
    levelsButton: 'مراحل',
    dailyChallengeButton: 'چالش امروز',
    dailyRewardButton: 'جایزه روزانه',
    settingsButton: 'تنظیمات',
    achievementsButton: 'دستاوردها',
    progressOfLevels: '{completed} از {total} مرحله',
    currentLevelLabel: 'در حال بازی: مرحله {number}',
    dailyRewardReady: 'جایزه امروز آماده است',
    gameFinishedKicker: 'مسیر کامل شد',
    gameFinishedTitle: 'تبریک، قهرمان!',
    gameFinishedBody: 'هر {total} مرحله را با موفقیت پشت سر گذاشتی.',
    gameFinishedButton: 'دیدن نقشهٔ مراحل',
    dailyChallengeDone: 'چالش امروز انجام شد',
    dailyChallengeNew: 'چالش تازه امروز',
    streakLabel: 'روز متوالی',
    totalScoreLabel: 'امتیاز کل',
  },

  levelMap: {
    title: 'مراحل',
    worldLabel: 'مرحله‌های {from} تا {to}',
    completed: 'تکمیل‌شده',
    current: 'در حال بازی',
    unlocked: 'باز',
    locked: 'قفل',
    lockedMessage: 'برای باز شدن این مرحله، مرحله‌های قبلی را کامل کن.',
    bestScoreLabel: 'بهترین امتیاز',
    targetWordsLabel: '{count} کلمه اصلی',
    legend: 'راهنما',
  },

  game: {
    lettersHint: 'حروف را انتخاب کن',
    wheelHint: 'کلمه‌ها',
    dragHint: 'انگشتت را روی حروف بکش و کلمه بساز',
    slotsEmpty: 'کلمه را اینجا ببین',
    clearButton: 'پاک کردن',
    submitButton: 'بررسی',
    hintButton: 'راهنما',
    progressLabel: 'کلمات پیدا‌شده',
    targetProgress: '{found} از {total}',
    bonusFound: 'کلمه امتیازی!',
    combo: 'کمبو ×{value}',
    correct: 'آفرین! کلمه درست است',
    wrong: 'این کلمه نامعتبر است',
    alreadyFound: 'این کلمه را قبلاً پیدا کرده‌ای',
    notInDictionary: 'این کلمه در دیکشنری بازی نیست',
    notInLevel: 'این کلمه با حروف این مرحله ساخته نمی‌شود',
    lettersUnavailable: 'برای این کلمه، حرف بیشتری لازم داری',
    tooShort: 'کلمه باید حداقل {length} حرف باشد',
    tooLong: 'این کلمه از حروف مرحله بلندتر است',
    invalidCharacters: 'فقط حروف فارسی مجاز است',
    emptyWord: 'اول چند حرف انتخاب کن',
    tutorialStepLetters: 'انگشتت را روی حروف بکش یا روی آن‌ها بزن.',
    tutorialStepSubmit: 'انگشتت را برداری، کلمه خودش ثبت می‌شود؛ یا دکمه «بررسی» را بزن.',
    tutorialStepNext: 'همه کلمات مرحله را پیدا کن تا جایزه بگیری.',
    allWordsFound: 'همه کلمات مرحله پیدا شد!',
    leaveTitle: 'از مرحله خارج می‌شوی؟',
    leaveBody: 'پیشرفت این مرحله ذخیره نمی‌شود.',
    wordsFoundTitle: 'کلمات پیدا‌شده',
    bonusWordsTitle: 'کلمات امتیازی',
    useHintTitle: 'راهنما',
    useHintBody: 'برای آشکار شدن یک حرف، {cost} سکه پرداخت می‌شود.',
    useHintConfirm: 'استفاده از راهنما',
    noCoinsForHint: 'برای راهنما سکه کافی نداری',
    hintApplied: 'راهنما فعال شد؛ کاشی‌های روشن را به ترتیب بزن',
    hintAlreadyApplied: 'همه حروف آشکار شده است',
    hintButtonWithCost: 'راهنما · {cost}',
    hintSheetTitle: 'راهنمای هوشمند',
    hintSheetSubtitle: 'هر راهنما همان لحظه از سکه‌هایت کم می‌شود؛ ارزان‌ترین راه را انتخاب کن.',
    hintRevealLetterTitle: 'حرف بعدی',
    hintSmartHelpTitle: 'راهنمای قدم‌به‌قدم',
    hintRevealWordTitle: 'آشکار کردن واژه',
    hintRevealLetterDesc: 'یک حرف از نزدیک‌ترین واژه به تو آشکار می‌شود و روی چرخ روشن می‌شود.',
    hintSmartHelpDesc: 'الگوی واژه و ترتیب حروفش نشان داده می‌شود؛ کاشی‌ها یکی‌یکی روی چرخ روشن می‌شوند.',
    hintRevealWordDesc: 'همه حروف یک واژه آشکار می‌شود؛ امتیاز آن واژه کمتر می‌شود.',
    hintCostLabel: '{cost} سکه',
    hintUseButton: 'بخر',
    hintNoCoinsButton: 'سکه کافی نیست',
    hintOptionLabel: '{title}، {cost} سکه',
    hintUseLabel: 'خرید {title}',
    hintEarnCoinsTip: 'با پیدا کردن کلمه‌ها، تکمیل مرحله‌ها و جایزه روزانه سکه می‌گیری.',
    hintGuideTitle: 'واژه‌ای که راهنما نشان می‌دهد',
    hintGuideMeta: '{length} حرفی · {left} حرف مانده',
    hintGuideDismiss: 'بستن راهنما',
    hintSpent: '{cost} سکه کم شد',
    hintFoundWord: 'واژه راهنما پیدا شد!',
    progressRing: 'پیشرفت واژه‌های مرحله',
  },

  result: {
    completedTitle: 'آفرین! مرحله کامل شد',
    gameFinishedTitle: 'تبریک! بازی تمام شد',
    gameFinishedSubtitle: 'همهٔ {total} مرحله را پشت سر گذاشتی؛ تو یک قهرمانی!',
    autoNextLevelHint: 'تا چند لحظهٔ دیگر وارد مرحلهٔ {number} می‌شوی.',
    autoHomeHint: 'تا چند لحظهٔ دیگر به صفحهٔ اصلی برمی‌گردی.',
    failedTitle: 'مرحله کامل نشد',
    completedSubtitle: 'عالی بود! به همین ترتیب ادامه بده.',
    failedSubtitle: 'کمی دیگر تمرین کن و دوباره امتحان کن.',
    shareResult: 'اشتراک‌گذاری نتیجه',
    shareMessage: 'در بازی «کلمه‌ساز» مرحله {level} را با {score} امتیاز و {stars} ستاره تمام کردم! تو هم امتحان کن.',
    starsLabel: 'ستاره‌های این مرحله',
    scoreLabel: 'امتیاز',
    coinsLabel: 'سکه',
    bonusLabel: 'کلمات امتیازی',
    maxComboLabel: 'بهترین کمبو',
    wordsTitle: 'کلمات مرحله',
    nextLevelButton: 'مرحله بعد',
    retryButton: 'تکرار مرحله',
    homeButton: 'خانه',
    wordsFoundOf: '{found} از {total} کلمه',
    newBestScore: 'رکورد جدید!',
    levelUnlocked: 'مرحله {number} باز شد',
  },

  hearts: {
    label: 'قلب',
    noHeartsTitle: 'قلب کافی نداری',
    noHeartsBody: 'برای بازی به قلب نیاز داری. قلب‌ها خودشان پر می‌شوند.',
    nextHeartIn: 'قلب بعدی تا {time}',
    heartsFull: 'قلب‌هایت پر است',
    watchAdForHeart: 'دریافت یک قلب',
    notEnoughHearts: 'قلب کافی نداری',
    refilled: '{count} قلب پر شد',
    freeLevelNote: 'این مرحله آموزشی رایگان است',
    buyTitle: 'پر کردن قلب‌ها',
    buyBody: 'با {cost} سکه همه قلب‌هایت را پر کن و بی‌وقفه بازی کن.',
    buyButton: 'پر کن با {cost} سکه',
    buyNotEnoughCoins: 'برای این کار سکه کافی نداری',
    buyDone: 'قلب‌هایت پر شد',
  },

  daily: {
    title: 'چالش امروز',
    subtitle: 'هر روز یک پازل تازه، فقط یک بار در روز',
    startButton: 'شروع چالش',
    completedTitle: 'چالش امروز انجام شد',
    completedBody: 'فردا یک پازل تازه در انتظار توست.',
    alreadyCompleted: 'امروز این چالش را انجام داده‌ای',
    comeBackTomorrow: 'فردا دوباره سر بزن',
    streakTitle: 'استریک روزانه',
    streakValue: '{days} روز متوالی',
    streakMilestone: 'استریک {days} روزه!',
    rewardTitle: 'جایزه روزانه',
    rewardSubtitle: 'هر روز وارد شو و جایزه بگیر',
    rewardDayLabel: 'روز {day} از {total}',
    rewardClaimed: 'جایزه امروز دریافت شد',
    rewardClaimButton: 'دریافت {coins} سکه',
    claimedMessage: 'جایزه امروز ثبت شد',
    nextRewardIn: 'جایزه بعدی فردا',
  },

  stats: {
    title: 'آمار من',
    subtitle: 'خلاصه‌ای از بازی‌های تو',
    wordsFound: 'کلمه پیدا شده',
    bonusWords: 'کلمه امتیازی',
    bestCombo: 'بهترین کمبو',
    gamesPlayed: 'بازی‌های شروع‌شده',
    gamesCompleted: 'مرحله‌های تکمیل‌شده',
    hintsUsed: 'راهنماهای استفاده‌شده',
    totalScore: 'امتیاز کل',
    coins: 'سکه‌ها',
    streak: 'روزهای متوالی',
    completion: 'پیشرفت مرحله‌ها',
    wordsPerGame: 'میانگین کلمه در هر بازی: {count}',
    starsTotal: '{earned} از {possible} ستاره',
    emptyTitle: 'هنوز بازی نکرده‌ای',
    emptyBody: 'اولین مرحله را بازی کن تا آمارت اینجا پر شود.',
    emptyAction: 'شروع بازی',
  },

  achievements: {
    title: 'دستاوردها',
    subtitle: '{unlocked} از {total} دستاورد باز شده',
    unlockedAt: 'باز شده',
    locked: 'قفل',
    progress: '{current} از {target}',
    newBadge: 'جدید',
    emptyState: 'هنوز دستاوردی باز نشده. بازی را شروع کن!',
  },

  settings: {
    title: 'تنظیمات',
    soundLabel: 'صدا',
    soundDescription: 'صدای انتخاب حرف، پاسخ درست و جایزه',
    vibrationLabel: 'لرزش',
    vibrationDescription: 'بازخورد لمسی هنگام بازی',
    reducedMotionLabel: 'کاهش انیمیشن',
    reducedMotionDescription: 'انیمیشن‌های بازی ساده‌تر می‌شوند',
    notificationsLabel: 'اعلان‌ها',
    notificationsDescription: 'یادآوری چالش روزانه (در نسخه‌های بعدی)',
    aboutLabel: 'درباره بازی',
    privacyLabel: 'حریم خصوصی',
    resetLabel: 'پاک‌کردن پیشرفت',
    resetDescription: 'همه مراحل، سکه‌ها و دستاوردها پاک می‌شوند',
    resetConfirmTitle: 'پاک‌کردن پیشرفت؟',
    resetConfirmBody: 'این کار قابل بازگشت نیست. مطمئنی؟',
    resetConfirmButton: 'بله، پاک کن',
    versionLabel: 'نسخه {version}',
    unavailableInMvp: 'در نسخه‌های بعدی فعال می‌شود',
    statsLabel: 'آمار من',
    statsDescription: 'کلمه‌ها، کمبو، راهنماها و پیشرفت کلی',
    shareLabel: 'اشتراک‌گذاری بازی',
    shareDescription: 'لینک بازی را برای دوستانت بفرست',
    shareMessage: 'بازی «کلمه‌ساز» را بازی کن! کلمه بساز و مرحله‌ها را باز کن: {link}',
    rateLabel: 'امتیاز دادن',
    rateDescription: 'بازی را در کافه‌بازار امتیاز بده',
    rateUnavailable: 'فروشگاه روی این دستگاه در دسترس نیست؛ می‌توانی در کافه‌بازار جست‌وجو کنی',
    storeUrl: 'https://cafebazaar.ir/app/ir.kalamesaz.game',
  },

  about: {
    title: 'درباره بازی',
    intro:
      'کلمه‌ساز یک بازی کلمات فارسی است: در هر مرحله چند حرف در اختیار داری و باید کلمه‌های درست فارسی را با همان حروف بسازی.',
    featuresTitle: 'چه چیزی در بازی هست؟',
    feature1: 'بیش از ۵۰ مرحله با درجه سختی آسان تا حرفه‌ای',
    feature2: 'چالش روزانه تازه و جایزه هفتگی',
    feature3: 'راهنمای خریداری‌شده با سکه‌ای که در بازی به دست می‌آوری',
    feature4: 'بدون نیاز به اینترنت؛ همه داده‌ها روی دستگاه تو می‌مانند',
    creditsTitle: 'درباره واژه‌ها',
    creditsBody:
      'واژه‌های بازی به‌صورت دستی و با تمرکز بر واژه‌های رایج و مناسب بازی عمومی انتخاب شده‌اند.',
    contactTitle: 'ارتباط با ما',
    contactBody: 'برای گزارش واژه نامناسب یا پیشنهاد واژه تازه با ما در تماس باش.',
    developerLabel: 'سازنده',
  },

  privacy: {
    title: 'حریم خصوصی',
    updatedAt: 'آخرین به‌روزرسانی: مهر ۱۴۰۵',
    section1Title: 'جمع‌آوری اطلاعات',
    section1Body:
      'این بازی هیچ اطلاعات شخصی از تو جمع‌آوری، ارسال یا با دیگران به اشتراک نمی‌گذارد. بازی در حالت آفلاین کامل کار می‌کند.',
    section2Title: 'داده‌های روی دستگاه',
    section2Body:
      'پیشرفت بازی، سکه‌ها، قلب‌ها و تنظیمات فقط روی حافظه داخلی دستگاه تو ذخیره می‌شوند و با پاک‌کردن بازی از بین می‌روند.',
    section3Title: 'مجوزها',
    section3Body:
      'این برنامه به هیچ مجوز دسترسی به اطلاعات حساس (مکان، مخاطبین، دوربین، میکروفون و پیام‌ها) نیازی ندارد.',
    section4Title: 'تبلیغات و خرید درون‌برنامه‌ای',
    section4Body:
      'در نسخه فعلی تبلیغ یا خرید درون‌برنامه‌ای فعال نیست. اگر در نسخه‌های بعدی اضافه شود، متن همین صفحه پیش از انتشار به‌روزرسانی می‌شود.',
    section5Title: 'کودکان',
    section5Body:
      'بازی محتوای مناسب عموم دارد و هیچ داده‌ای از کاربران، از جمله کودکان، جمع نمی‌کند.',
  },

  errors: {
    genericTitle: 'مشکلی پیش آمد',
    genericBody: 'لطفاً یک بار دیگر تلاش کن.',
    storageCorrupted: 'داده‌های بازی بازنشانی شد',
    soundUnavailable: 'پخش صدا در این دستگاه فعال نیست',
    crashTitle: 'یک لحظه!',
    crashBody: 'مشکلی پیش آمد ولی نگران نباش؛ پیشرفتت ذخیره شده است. دوباره تلاش کن.',
    crashRetry: 'تلاش دوباره',
    crashDetails: 'جزئیات فنی',
  },

  accessibility: {
    letterTile: 'حرف {letter}',
    letterTileSelected: 'حرف {letter} انتخاب شده',
    coinCounter: '{count} سکه',
    heartCounter: '{count} از {max} قلب',
    scoreCounter: 'امتیاز {count}',
    lockedLevel: 'مرحله {number} قفل است',
    completedLevel: 'مرحله {number} تکمیل شده است',
    currentLevel: 'مرحله {number} در حال بازی',
    hintButton: 'خرید راهنما با {cost} سکه',
    submitButton: 'بررسی کلمه ساخته‌شده',
    clearButton: 'پاک‌کردن کلمه ساخته‌شده',
    coinChange: 'سکه‌ها: {count}',
    hintGuide: 'راهنمای واژه {pattern}؛ کاشی بعدی روشن است',
    statCard: '{label}: {value}',
    starEarned: '{count} ستاره از ۳',
  },
};

export type AppStrings = typeof faStrings;
