/**
 * Export the real level catalog to a browser-consumable module for preview-v2.
 *
 * The preview must never maintain its own hand-copied level answers. Re-run this
 * before serving so the browser route stays aligned with src/data/levels/levels.ts.
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { LEVELS } from '../src/data/levels/levels';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const target = resolve(root, 'preview-v2/levels.js');
const browserLevels = LEVELS.map(level => ({
  id: level.id,
  title: level.title,
  difficulty: level.difficulty,
  letters: level.letters,
  targetWords: level.targetWords,
  bonusWords: level.bonusWords,
  minWordLength: level.minWordLength,
  maxWordLength: level.maxWordLength,
  hintCost: level.hintCost,
  scoreReward: level.scoreReward,
  coinReward: level.coinReward,
}));

writeFileSync(
  target,
  `// Generated by tools/export-preview-levels.mts from src/data/levels/levels.ts. Do not edit by hand.\nexport const PREVIEW_LEVELS = ${JSON.stringify(browserLevels, null, 2)};\n`,
  'utf8',
);
console.log(`دادهٔ ${browserLevels.length} مرحله برای Preview v2 نوشته شد: ${target}`);
